### ISSUE TITLE
[Bug] Pod crashes when used in Scaleway

### ISSUE THREAD

**Issue by devpikachu** [kubecost/features-bugs#24]
### Problem Statement

Currently, Kubecost doesn't support [Scaleway](https://www.scaleway.com/en/kubernetes-kapsule/) as a provider and the pod crashes indefinitely:

```
2023/08/29 13:20:39 maxprocs: Leaving GOMAXPROCS=2: CPU quota undefined
[90m2023-08-29T13:20:39.778948267Z[0m [1m???[0m Log level set to info
[90m2023-08-29T13:20:39.779009061Z[0m [32mINF[0m Starting Kubecost cost-model version 1.105.2 (94410c5)
[90m2023-08-29T13:20:39.780996678Z[0m [32mINF[0m Prometheus/Thanos Client Max Concurrency set to 5
[90m2023-08-29T13:20:39.78686936Z[0m [32mINF[0m Success: retrieved the 'up' query against prometheus at: http://prometheus-operated.prometheus.traefik.mesh:9090/
[90m2023-08-29T13:20:39.793785625Z[0m [32mINF[0m Retrieved a prometheus config file from: http://prometheus-operated.prometheus.traefik.mesh:9090/
[90m2023-08-29T13:20:39.803457139Z[0m [32mINF[0m Using scrape interval of 60.000000
[90m2023-08-29T13:20:39.80406909Z[0m [32mINF[0m NAMESPACE: kubecost
[90m2023-08-29T13:20:40.104978244Z[0m [32mINF[0m Done waiting
[90m2023-08-29T13:20:40.105568815Z[0m [32mINF[0m Starting *v1.Namespace controller
[90m2023-08-29T13:20:40.105756237Z[0m [32mINF[0m Starting *v1.Node controller
[90m2023-08-29T13:20:40.10582145Z[0m [32mINF[0m Starting *v1.Pod controller
[90m2023-08-29T13:20:40.10590626Z[0m [32mINF[0m Starting *v1.Service controller
[90m2023-08-29T13:20:40.106037486Z[0m [32mINF[0m Starting *v1.ConfigMap controller
[90m2023-08-29T13:20:40.106141752Z[0m [32mINF[0m Starting *v1.DaemonSet controller
[90m2023-08-29T13:20:40.10621519Z[0m [32mINF[0m Starting *v1.Deployment controller
[90m2023-08-29T13:20:40.106333703Z[0m [32mINF[0m Starting *v1.StatefulSet controller
[90m2023-08-29T13:20:40.106450723Z[0m [32mINF[0m Starting *v1.ReplicaSet controller
[90m2023-08-29T13:20:40.106565679Z[0m [32mINF[0m Starting *v1.PersistentVolume controller
[90m2023-08-29T13:20:40.106637394Z[0m [32mINF[0m Starting *v1.PersistentVolumeClaim controller
[90m2023-08-29T13:20:40.106684403Z[0m [32mINF[0m Starting *v1.StorageClass controller
[90m2023-08-29T13:20:40.106728666Z[0m [32mINF[0m Starting *v1.Job controller
[90m2023-08-29T13:20:40.106767749Z[0m [32mINF[0m Starting *v1beta1.PodDisruptionBudget controller
[90m2023-08-29T13:20:40.106813194Z[0m [32mINF[0m Starting *v1.ReplicationController controller
[90m2023-08-29T13:20:40.10943267Z[0m [32mINF[0m Found ProviderID starting with "scaleway", using Scaleway Provider
[90m2023-08-29T13:20:40.12136691Z[0m [32mINF[0m No asset-report-configs configmap found at install time, using existing configs: configmaps "asset-report-configs" not found
[90m2023-08-29T13:20:40.131145807Z[0m [32mINF[0m No advanced-report-configs configmap found at install time, using existing configs: configmaps "advanced-report-configs" not found
[90m2023-08-29T13:20:40.217114238Z[0m [32mINF[0m No saved-report-configs configmap found at install time, using existing configs: configmaps "saved-report-configs" not found
[90m2023-08-29T13:20:40.416305838Z[0m [32mINF[0m No pricing-configs configmap found at install time, using existing configs: configmaps "pricing-configs" not found
[90m2023-08-29T13:20:40.614670714Z[0m [32mINF[0m No cloud-cost-report-configs configmap found at install time, using existing configs: configmaps "cloud-cost-report-configs" not found
[90m2023-08-29T13:20:40.815326476Z[0m [32mINF[0m No product-configs configmap found at install time, using existing configs: configmaps "product-configs" not found
[90m2023-08-29T13:20:41.014819183Z[0m [32mINF[0m No alert-configs configmap found at install time, using existing configs: configmaps "alert-configs" not found
[90m2023-08-29T13:20:41.21705655Z[0m [32mINF[0m No recurring-budget-rule-configs configmap found at install time, using existing configs: configmaps "recurring-budget-rule-configs" not found
[90m2023-08-29T13:20:41.416224485Z[0m [32mINF[0m No group-report-configs configmap found at install time, using existing configs: configmaps "group-report-configs" not found
[90m2023-08-29T13:20:41.616794296Z[0m [32mINF[0m No budget-configs configmap found at install time, using existing configs: configmaps "budget-configs" not found
[90m2023-08-29T13:20:41.813632291Z[0m [32mINF[0m No group-filters configmap found at install time, using existing configs: configmaps "group-filters" not found
[90m2023-08-29T13:20:42.015814434Z[0m [32mINF[0m No metrics-config configmap found at install time, using existing configs: configmaps "metrics-config" not found
[90m2023-08-29T13:20:42.214287803Z[0m [32mINF[0m No app-configs configmap found at install time, using existing configs: configmaps "app-configs" not found
[90m2023-08-29T13:20:42.547232903Z[0m [32mINF[0m Init: AggregateCostModel cache warming disabled
panic: provider is required: failed to convert cost model provider

goroutine 1 [running]:
github.com/kubecost/kubecost-cost-model/pkg/cmd/costmodel.Initialize()
	/home/runner/work/release-scripts/release-scripts/release-scripts/workdir-prod-tag/kubecost/kubecost-cost-model/pkg/cmd/costmodel/costmodel.go:1577 +0x2db9
github.com/kubecost/kubecost-cost-model/pkg/cmd/costmodel.Execute(0x1?)
	/home/runner/work/release-scripts/release-scripts/release-scripts/workdir-prod-tag/kubecost/kubecost-cost-model/pkg/cmd/costmodel/costmodel.go:2028 +0xf7
github.com/kubecost/kubecost-cost-model/pkg/cmd.Execute.newCostModelCommand.func1(0xc0000e3400?, {0x330f85e?, 0x4?, 0x330f862?})
	/home/runner/work/release-scripts/release-scripts/release-scripts/workdir-prod-tag/kubecost/kubecost-cost-model/pkg/cmd/commands.go:43 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc000fb6600, {0x5a1a300, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000fb7200)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
github.com/opencost/opencost/pkg/cmd.Execute(0x0?, {0xc00103fee0, 0x3, 0x3})
	/home/runner/work/release-scripts/release-scripts/release-scripts/workdir-prod-tag/kubecost/opencost/pkg/cmd/commands.go:61 +0x3a5
github.com/kubecost/kubecost-cost-model/pkg/cmd.Execute()
	/home/runner/work/release-scripts/release-scripts/release-scripts/workdir-prod-tag/kubecost/kubecost-cost-model/pkg/cmd/commands.go:27 +0x1e5
main.main()
	/home/runner/work/release-scripts/release-scripts/release-scripts/workdir-prod-tag/kubecost/kubecost-cost-model/cmd/costmodel/main.go:12 +0x13
```

### Solution Description

Add [Scaleway](https://www.scaleway.com/en/kubernetes-kapsule/) as a supported provider for Kubecost.

**Comment by kwombach12** [comment]
@devpikachu We do actually support Scaleway - this appears to be a bug. I will file in our backlog and have someone on the team look at this.

**Comment by chipzoller** [comment]
Should we close this in that case?

**Comment by kwombach12** [comment]
@chipzoller I updated the tags to reflect this is a bug, I suggest we leave this open until we resolve it so that users can track progress

**Comment by chipzoller** [comment]
That's fine, but we need to update issue titles when that occurs. I've done so here.

**Comment by chipzoller** [comment]
Since this is an application bug and not a Helm chart one, I've transferred here.

**Comment by AjayTripathy** [comment]
https://github.com/kubecost/kubecost-cost-model/pull/1943

Fix available here. Scheduled for 108 release.
