### ISSUE TITLE
Support OKE (Oracle Cloud Kubernetes Engine)

### ISSUE THREAD

**Issue by shariqmus** [kubecost/features-bugs#53]
### Problem Statement

After installing on OKE (1.25), kubecost-cost-analyzer-564d46f856-tfz2b pod is in Crashloopbackoff

```
helm install kubecost cost-analyzer \
--repo https://kubecost.github.io/cost-analyzer/ \
--namespace kubecost --create-namespace \
--set kubecostToken="
```

Logs:

```
2024/02/08 12:40:28 maxprocs: Leaving GOMAXPROCS=16: CPU quota undefined
2024-02-08T12:40:28.246367012Z ??? Log level set to info
2024-02-08T12:40:28.246404382Z INF Starting Kubecost cost-model version kcm-1958af0e66_core-fff1b67d10_oc-c6d7ad89ce (1958af0e)
2024-02-08T12:40:28.246417647Z INF waterfowl is enabled, it will handle /reports and /budgets
2024-02-08T12:40:28.246483531Z INF Prometheus/Thanos Client Max Concurrency set to 5
2024-02-08T12:40:28.251170001Z INF Success: retrieved the 'up' query against prometheus at: http://kubecost-prometheus-server.kubecost
2024-02-08T12:40:28.253232657Z INF Retrieved a prometheus config file from: http://kubecost-prometheus-server.kubecost
2024-02-08T12:40:28.256022745Z INF Using scrape interval of 60.000000
2024-02-08T12:40:28.256362938Z INF NAMESPACE: kubecost
2024-02-08T12:40:28.456924826Z INF Done waiting
2024-02-08T12:40:28.45700098Z INF Starting *v1.Pod controller
2024-02-08T12:40:28.45704325Z INF Starting *v1.Service controller
2024-02-08T12:40:28.457047508Z INF Starting *v1.Namespace controller
2024-02-08T12:40:28.457069239Z INF Starting *v1.Node controller
2024-02-08T12:40:28.457012892Z INF Starting *v1.Deployment controller
2024-02-08T12:40:28.457092452Z INF Starting *v1.PersistentVolumeClaim controller
2024-02-08T12:40:28.457105608Z INF Starting *v1beta1.PodDisruptionBudget controller
2024-02-08T12:40:28.457135494Z INF Starting *v1.ConfigMap controller
2024-02-08T12:40:28.457130084Z INF Starting *v1.Job controller
2024-02-08T12:40:28.457157325Z INF Starting *v1.DaemonSet controller
2024-02-08T12:40:28.45716002Z INF Starting *v1.StatefulSet controller
2024-02-08T12:40:28.457152846Z INF Starting *v1.ReplicaSet controller
2024-02-08T12:40:28.457159018Z INF Starting *v1.PersistentVolume controller
2024-02-08T12:40:28.457157746Z INF Starting *v1.StorageClass controller
2024-02-08T12:40:28.457252996Z INF Starting *v1.ReplicationController controller
2024-02-08T12:40:28.458998382Z INF Found ProviderID starting with "oracle", using Oracle Provider
2024-02-08T12:40:28.462851588Z INF No app-configs configmap found at install time, using existing configs: configmaps "app-configs" not found
2024-02-08T12:40:28.465696691Z INF No product-configs configmap found at install time, using existing configs: configmaps "product-configs" not found
2024-02-08T12:40:28.660801443Z INF No alert-configs configmap found at install time, using existing configs: configmaps "alert-configs" not found
2024-02-08T12:40:28.861397767Z INF No group-filters configmap found at install time, using existing configs: configmaps "group-filters" not found
2024-02-08T12:40:29.067515646Z INF No account-mapping configmap found at install time, using existing configs: configmaps "account-mapping" not found
2024-02-08T12:40:29.261912332Z INF No pricing-configs configmap found at install time, using existing configs: configmaps "pricing-configs" not found
2024-02-08T12:40:29.461390566Z INF No metrics-config configmap found at install time, using existing configs: configmaps "metrics-config" not found
2024-02-08T12:40:30.931061733Z INF Init: AggregateCostModel cache warming disabled
panic: provider is required: failed to convert cost model provider

goroutine 1 [running]:
github.com/kubecost/kubecost-cost-model/pkg/cmd/costmodel.Initialize()
    /app/kubecost-cost-model/pkg/cmd/costmodel/costmodel.go:1546 +0x332e
github.com/kubecost/kubecost-cost-model/pkg/cmd/costmodel.Execute(0x1?)
    /app/kubecost-cost-model/pkg/cmd/costmodel/costmodel.go:2143 +0xf2
github.com/kubecost/kubecost-cost-model/pkg/cmd.Execute.newCostModelCommand.func1(0xc000f1f800?, {0x4e01555?, 0x4?, 0x4e01559?})
    /app/kubecost-cost-model/pkg/cmd/commands.go:71 +0x2f
github.com/spf13/cobra.(*Command).execute(0xc001286900, {0x80cab80, 0x0, 0x0})
    /go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:916 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0012ba600)
    /go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:1040 +0x38d
github.com/spf13/cobra.(*Command).Execute(...)
    /go/pkg/mod/github.com/spf13/cobra@v1.6.0/command.go:968
github.com/opencost/opencost/pkg/cmd.Execute(0x219d2399a78ed388?, {0xc001081eb8, 0x8, 0x8})
    /app/opencost/pkg/cmd/commands.go:61 +0x3a5
github.com/kubecost/kubecost-cost-model/pkg/cmd.Execute()
    /app/kubecost-cost-model/pkg/cmd/commands.go:45 +0x3ab
main.main()
    /app/kubecost-cost-model/cmd/costmodel/main.go:14 +0x13
Stream closed EOF for kubecost/kubecost-cost-analyzer-564d46f856-tfz2b (cost-model)


```

### Solution Description

Support OKE as a provider

### Troubleshooting

- [X] I have read and followed the [issue guidelines](https://github.com/kubecost/features-bugs/blob/main/ISSUE_GUIDELINES.md) and this is a feature request only for the Kubecost application.
- [X] I have searched other issues in this repository and mine is not recorded.

**Comment by mattray** [comment]
OCI is still in development and not currently supported, but we are looking into this. We'll check back with Oracle and do more testing before official release.

**Comment by chipzoller** [comment]
Hello, in an effort to consolidate our bug and feature request tracking, we are deprecating using GitHub to track tickets. If this issue is still outstanding and you have not done so already, please raise a request at https://support.kubecost.com/.
